name: Daily USOS Briefing

on:
  schedule:
    # 매일 한국 시간 자정 (KST 00:00) = UTC 15:00
    # GitHub 서버는 영국 시간(UTC)을 쓰므로 15:00로 설정해야 한국 자정에 돕니다.
    - cron: '0 15 * * *'
  # 수동으로 버튼 눌러서 실행 가능하게 함 (테스트용)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot Script
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python daily_bot.py